import React, { useState } from 'react';
import { Shield, RefreshCw, Truck, FileText, X } from 'lucide-react';

type PolicyKey = 'privacy' | 'refund' | 'shipping' | 'terms';

const POLICIES: { key: PolicyKey; title: string; icon: React.ReactNode }[] = [
  { key: 'privacy',  title: 'Privacy Policy',          icon: <Shield size={18} /> },
  { key: 'refund',   title: 'Refund & Return Policy',  icon: <RefreshCw size={18} /> },
  { key: 'shipping', title: 'Service Delivery Policy', icon: <Truck size={18} /> },
  { key: 'terms',    title: 'Terms & Conditions',      icon: <FileText size={18} /> },
];

const POLICY_CONTENT: Record<PolicyKey, { sections: { heading: string; body: string }[] }> = {
  privacy: {
    sections: [
      {
        heading: '1. Information We Collect',
        body: 'We collect information you provide directly to us, such as your name, email address, and payment details when you subscribe to our services. We also collect usage data, including pages visited, features used, and session duration.',
      },
      {
        heading: '2. How We Use Your Information',
        body: 'Your information is used to provide and improve our services, process payments, send transactional emails, and respond to support requests. We do not sell your personal data to third parties.',
      },
      {
        heading: '3. Data Storage & Security',
        body: 'All data is stored on secure cloud infrastructure (Railway/Vercel). Passwords are hashed using industry-standard algorithms. Payment data is handled exclusively by PayFast and Lemon Squeezy — we never store card numbers on our servers.',
      },
      {
        heading: '4. Cookies',
        body: 'We use essential cookies for authentication and session management. Analytics cookies may be used to understand usage patterns. You may disable non-essential cookies in your browser settings.',
      },
      {
        heading: '5. Your Rights',
        body: 'You may request access to, correction of, or deletion of your personal data at any time by contacting us at shayat10943@gmail.com. We will respond within 7 business days.',
      },
      {
        heading: '6. Contact',
        body: 'For privacy-related queries: shayat10943@gmail.com | Office: Flate No.26-D, Street 8, Askari 4,Chaklala, Rawalpindi, Punjab, Pakistan | Phone: +92 332 1326146',
      },
    ],
  },
  refund: {
    sections: [
      {
        heading: '1. Subscription Cancellation',
        body: 'You may cancel your subscription at any time from your account dashboard. Cancellation takes effect at the end of the current billing period. No further charges will be made after cancellation.',
      },
      {
        heading: '2. Refund Eligibility',
        body: 'Refund requests submitted within 7 days of initial purchase are eligible for a full refund, provided the service has not been substantially used (fewer than 3 AI sessions or exam papers generated). Refunds are not available after 7 days.',
      },
      {
        heading: '3. How to Request a Refund',
        body: 'Email shayat10943@gmail.com with subject line "Refund Request — [Product Name]" and include your registered email and order ID. We process refunds within 5–7 business days back to the original payment method.',
      },
      {
        heading: '4. Non-Refundable Items',
        body: 'Partial months, one-time add-ons, and custom consulting engagements are non-refundable once delivered.',
      },
      {
        heading: '5. Disputes',
        body: 'If you believe you have been charged in error, contact us before initiating a chargeback. We are committed to resolving billing disputes fairly and promptly.',
      },
    ],
  },
  shipping: {
    sections: [
      {
        heading: '1. Digital Service Delivery',
        body: 'All products on hayatcloud.com are digital AI SaaS services. There are no physical goods to ship. Access to purchased services is granted immediately upon successful payment confirmation.',
      },
      {
        heading: '2. Account Activation',
        body: 'Upon payment, you will receive a confirmation email with login credentials or an activation link within 5 minutes. If you do not receive access within 30 minutes, please contact support.',
      },
      {
        heading: '3. Service Availability',
        body: 'Our platforms target 99.5% uptime. Scheduled maintenance, if any, will be announced at least 24 hours in advance via email. Emergency maintenance may occur without prior notice.',
      },
      {
        heading: '4. AI-Generated Deliverables',
        body: 'Documents, exam papers, reports, and design packages generated by our AI agents are delivered digitally within the platform interface and may be downloaded as PDF, DOCX, or PPTX files where applicable.',
      },
      {
        heading: '5. Support Response Times',
        body: 'Email support: within 24 hours on business days. Priority support (Pro/Studio plans): within 4 hours. Business hours are Monday–Saturday, 9 AM–6 PM PKT.',
      },
    ],
  },
  terms: {
    sections: [
      {
        heading: '1. Acceptance of Terms',
        body: 'By accessing or using any service on hayatcloud.com, you agree to be bound by these Terms & Conditions. If you do not agree, please discontinue use immediately.',
      },
      {
        heading: '2. Permitted Use',
        body: 'Our services are for lawful personal and commercial use only. You may not reverse-engineer, resell, or redistribute our AI platforms or their outputs for commercial purposes without written permission.',
      },
      {
        heading: '3. Account Responsibility',
        body: 'You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorized access or suspected breach.',
      },
      {
        heading: '4. AI-Generated Content Disclaimer',
        body: 'Content generated by our AI agents (exam papers, financial reports, architectural designs) is provided for informational and educational purposes. Users should verify outputs before relying on them for professional, legal, or financial decisions.',
      },
      {
        heading: '5. Intellectual Property',
        body: 'All platform code, branding, and system design are the intellectual property of Shaukat Hayat / HayatCloud. AI-generated output documents belong to the subscribing user.',
      },
      {
        heading: '6. Limitation of Liability',
        body: 'HayatCloud shall not be liable for indirect, incidental, or consequential damages arising from use of our services. Our total liability is limited to the subscription fees paid in the 30 days preceding any claim.',
      },
      {
        heading: '7. Governing Law',
        body: 'These terms are governed by the laws of the Islamic Republic of Pakistan. Any disputes shall be subject to the exclusive jurisdiction of courts in Rawalpindi / Islamabad.',
      },
      {
        heading: '8. Changes to Terms',
        body: 'We reserve the right to update these terms at any time. Continued use of our services after changes constitutes acceptance. We will notify subscribers of material changes via email.',
      },
      {
        heading: '9. Contact',
        body: 'Legal enquiries: shayat10943@gmail.com | Flate No.26-D, Street 8, Askari 4,Chaklala, Rawalpindi, Punjab, Pakistan | Phone: +92 332 1326146',
      },
    ],
  },
};

const LegalModal: React.FC<{ policyKey: PolicyKey; onClose: () => void }> = ({ policyKey, onClose }) => {
  const policy = POLICIES.find((p) => p.key === policyKey)!;
  const content = POLICY_CONTENT[policyKey];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
      <div className="bg-white rounded-3xl max-w-2xl w-full max-h-[85vh] flex flex-col shadow-2xl">
        <div className="flex items-center justify-between p-8 border-b border-slate-100">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-indigo-50 rounded-xl flex items-center justify-center text-indigo-600">
              {policy.icon}
            </div>
            <h2 className="text-xl font-bold text-slate-900">{policy.title}</h2>
          </div>
          <button
            onClick={onClose}
            className="w-9 h-9 rounded-xl bg-slate-100 hover:bg-slate-200 flex items-center justify-center transition-colors"
          >
            <X size={16} />
          </button>
        </div>

        <div className="overflow-y-auto p-8 space-y-6">
          <p className="text-xs text-slate-400">Last updated: June 2025 | HayatCloud — hayatcloud.com</p>
          {content.sections.map((section) => (
            <div key={section.heading}>
              <h3 className="font-bold text-slate-900 mb-2">{section.heading}</h3>
              <p className="text-slate-600 leading-relaxed text-sm">{section.body}</p>
            </div>
          ))}
        </div>

        <div className="p-6 border-t border-slate-100">
          <button
            onClick={onClose}
            className="w-full py-3 bg-indigo-600 text-white rounded-xl font-bold hover:bg-indigo-700 transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};

const Legal: React.FC = () => {
  const [activePolicy, setActivePolicy] = useState<PolicyKey | null>(null);

  return (
    <>
      <section id="legal" className="py-16 bg-white border-t border-slate-100">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center mb-10">
            <h2 className="text-sm font-bold text-indigo-600 uppercase tracking-widest mb-2">Legal & Policies</h2>
            <p className="text-slate-500 text-sm">Click any policy below to read the full document</p>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {POLICIES.map((policy) => (
              <button
                key={policy.key}
                onClick={() => setActivePolicy(policy.key)}
                className="flex flex-col items-center gap-3 p-6 rounded-2xl border border-slate-200 hover:border-indigo-400 hover:bg-indigo-50 transition-all group"
              >
                <div className="w-10 h-10 bg-slate-100 group-hover:bg-indigo-100 rounded-xl flex items-center justify-center text-slate-500 group-hover:text-indigo-600 transition-colors">
                  {policy.icon}
                </div>
                <span className="text-sm font-semibold text-slate-700 group-hover:text-indigo-700 text-center transition-colors">
                  {policy.title}
                </span>
              </button>
            ))}
          </div>

          {/* Office & Contact */}
          <div className="mt-10 p-6 bg-slate-50 rounded-2xl border border-slate-200 text-center">
            <p className="text-sm font-bold text-slate-700 mb-1">HayatCloud — Local Office</p>
            <p className="text-slate-500 text-sm">
              Flate No.26-D, Street 8, Askari 4,Chaklala, Rawalpindi, Punjab, Pakistan
            </p>
            <p className="text-slate-500 text-sm mt-1">
              📞 +92 332 1326146 &nbsp;|&nbsp; ✉️ shayat10943@gmail.com
            </p>
          </div>
        </div>
      </section>

      {activePolicy && (
        <LegalModal policyKey={activePolicy} onClose={() => setActivePolicy(null)} />
      )}
    </>
  );
};

export default Legal;
